{% set name = "anchor-droplet-chip" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anchor_droplet_chip-{{ version }}.tar.gz
  sha256: 1e8e5bb35a254ec458bfbe5646c4391c3a3b96a0138793a24e1c9283aa8e9c50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=40.9.0
    - setuptools-scm
    - wheel
  run:
    - dask-core
    - fire
    - jupyterlab
    - matplotlib-base
    - napari
    - nd2
    - numpy
    - pandas
    # - pytest-qt
    - python >=3.8
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - tifffile
    - zarr-tools
    - zenodo_get

test:
  imports:
    - adc
    # - imreg_dft
  commands:
    - pip list
    # - pip check  # Fails due to pyqt6
  requires:
    - pip

about:
  home: https://pypi.org/project/anchor-droplet-chip
  summary: Segment organoids and measure intensities
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/BaroudLab/anchor-droplet-chip

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
